"""add CANCELLED to pr_po_data status_ai

Revision ID: 97c4e0657182
Revises: 9a1651046d97
Create Date: 2026-08-14 10:29:57.921493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c4e0657182'
down_revision = '9a1651046d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('kategori_id'))

    with op.batch_alter_table('pr_po_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_procurement_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pr_po_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_procurement_status'), ['procurement_status'], unique=False)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('kategori_id'), ['kategori_id', 'periode'], unique=True)

    # ### end Alembic commands ###
