"""sync baseline schema differences

Revision ID: 9a1651046d97
Revises: 
Create Date: 2026-08-13 15:34:40.613686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a1651046d97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('kategori_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('item_mapping', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.alter_column('tipe_formulir',
               existing_type=mysql.ENUM('CAPEX', 'OPEX'),
               nullable=True)

    with op.batch_alter_table('klasifikasi_log', schema=None) as batch_op:
        batch_op.alter_column('layer',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               comment='1=Rule Base, 2=Regex, 3=SVM',
               existing_nullable=True)
        batch_op.alter_column('processing_time',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='Waktu proses dalam detik',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('mapping_log', schema=None) as batch_op:
        batch_op.alter_column('rank_no',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('planning_detail', schema=None) as batch_op:
        batch_op.alter_column('kategori_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('month',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               nullable=True,
               comment='Bulan planning, contoh: Jan, Feb, Mar')
        batch_op.alter_column('status_realisasi',
               existing_type=mysql.ENUM('OPEN', 'PROSES', 'CLOSED', 'CANCELLED'),
               comment='Agregat status realisasi dari semua PR yang di-mapping ke item ini',
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))

    with op.batch_alter_table('planning_header', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('pr_po_data', schema=None) as batch_op:
        batch_op.alter_column('procurement_status',
               existing_type=mysql.ENUM('PR_CREATED', 'PO_ISSUED', 'PARTIAL_RECEIVED', 'GOODS_RECEIVED', 'COMPLETED'),
               nullable=True,
               existing_server_default=sa.text("'PR_CREATED'"))
        batch_op.alter_column('layer_klasifikasi',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_comment='1=Rule Base, 2=Regex, 3=SVM',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'manager'),
               nullable=False,
               existing_server_default=sa.text("'admin'"))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('admin', 'manager'),
               nullable=True,
               existing_server_default=sa.text("'admin'"))

    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('pr_po_data', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('layer_klasifikasi',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_comment='1=Rule Base, 2=Regex, 3=SVM',
               existing_nullable=True)
        batch_op.alter_column('procurement_status',
               existing_type=mysql.ENUM('PR_CREATED', 'PO_ISSUED', 'PARTIAL_RECEIVED', 'GOODS_RECEIVED', 'COMPLETED'),
               nullable=False,
               existing_server_default=sa.text("'PR_CREATED'"))

    with op.batch_alter_table('planning_header', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('planning_detail', schema=None) as batch_op:
        batch_op.alter_column('status_realisasi',
               existing_type=mysql.ENUM('OPEN', 'PROSES', 'CLOSED', 'CANCELLED'),
               comment=None,
               existing_comment='Agregat status realisasi dari semua PR yang di-mapping ke item ini',
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'"))
        batch_op.alter_column('month',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               nullable=False,
               comment=None,
               existing_comment='Bulan planning, contoh: Jan, Feb, Mar')
        batch_op.alter_column('kategori_id',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('mapping_log', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rank_no',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_nullable=True)

    with op.batch_alter_table('klasifikasi_log', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('processing_time',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment=None,
               existing_comment='Waktu proses dalam detik',
               existing_nullable=True)
        batch_op.alter_column('layer',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               comment=None,
               existing_comment='1=Rule Base, 2=Regex, 3=SVM',
               existing_nullable=True)

    with op.batch_alter_table('kategori', schema=None) as batch_op:
        batch_op.alter_column('tipe_formulir',
               existing_type=mysql.ENUM('CAPEX', 'OPEX'),
               nullable=False)

    with op.batch_alter_table('item_mapping', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('kategori_id',
               existing_type=mysql.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###